### ISSUE TITLE
implement Describe Database and Describe Schema 

### ISSUE THREAD

**Issue by dwayneberry** [omnisci/omniscidb#215]
Currently mapd via mapdql  supports \t and \d to get list of tables and to describe the ddl of individual tables.

SQL supports and calcite implements the DESCRIBE verb.

It would be great to hook the plumbing up in mapd to allow a sql `DESCRIBE` command to return the same basic details as the \t and \d currently do

**Comment by zhou2001** [comment]
how to assign this issue to me? My name is zhou2001.

. i reviewed the code a little bit
. looks like need implemented the DESCRIBER, the output will as same as \d 
. \t command is used to show tables. I will test is SHOW TABLES works in mapD now
. i plan to start to modify the yacc file and see if we could add this command
. looks like DESCRIBER and DESC is the already an keyword. 

Jianhua Zhou

**Comment by dwayneberry** [comment]
@zhou2001 You will need to fill in the contributor stuff so we can add you as a contributor I think 


You should not have to touch the yacc and lex stuff as that is for the DDL side of the product this should all go down the calcite path

**Comment by zhou2001** [comment]
Thanks Michael. I just noticed there is a yacc file, so if it is only for DDL commands, then I do need to touch it. DESCRIBE should consider a retrieve command like SELECT coomand, I may need to find the method to handle the SELECT command to add support for DESCRIBE command. Calcite path? I need to figure out what is this. 

Regards. 

Jianhua Zhou

**Comment by mikehinchey** [comment]
SQL SHOW commands are now supported for `show tables` and `show create table`.
