### ISSUE TITLE
[feature] Streaming support on JDBC driver

### ISSUE THREAD

**Issue by archenroot** [omnisci/omniscidb#313]
So, I would like to create new table from records in other table. I already realized Mapd is not deisgned for such task and I understand even the reasons behind that :-)

So in my design I will be working with tables as temporal buffers like:

INSERT NEW -> TABLE -> DELETE OBSOLETE

So I keep my table just up-to-date, but in general I can do select * from big_table on standard relational databases where the JDBC driver handles kind of streaming or pagination, etc. for me and can provide me with billions of records via chunks.

Do you plan to support such feature? At moment when I do in command line:
select * from fhv_tripdata;
I get;
`Exception: Query would require a scan without a limit on table(s): fhv_tripdata`

When I do on JDBC driver I simply get no records returned...

Not sure wheter is even good or bad idea to support it on Mapd...

Best regards,

Ladislav

**Comment by cdessanti** [comment]
If you don't specify a limit the JDBC driver would limit the results of your query to 100k records, so the query would return a result (I tried with DBeaver with a jdbc driver on a table containing NYC taxi data with 700M records).

About implementing pagination, it's not an easy task because the database doesn't support cursors, so you should do something to fake a cursor on the driver side. It's doable on simple projection queries but giving the idea to the devs that you have a scrollable cursor could be confusing

**Comment by randyzwitch** [comment]
>  I already realized Mapd is not deisgned for such task

This really isn't a correct statement, and I'd caution you to slow down a bit. :) 

You are correct that OmniSci isn't designed for the same use cases as some of the big enterprise transactional databases, and so we aren't a drop-in replacement to legacy data flows. But there are several ways of inserting records into existing tables, each with varying tradeoffs.

Using JDBC, you can insert records into a table, whether the source is another OmniSci table or Kafka or any other data source. I demonstrate this in my [Azure Data Fest](https://medium.com/omnisci/azure-datafest-2018-philly-real-time-operations-with-omnisci-29fbbd35a2b1) talk where I use StreamSets to read from a Kafka topic, then insert to OmniSci using JDBC. This is an effective, but not highly-performant, way to stream data into OmniSci with mini-batches of records.

As @cdessanti mentions, we don't do cursoring, but it sounds like this isn't the limiting factor in your workflow; rather, it seems like you are asking how to continously load data from a smaller, fresher table to a bigger historical table. I don't think there is a feature request needed to solve that problem, but I'd love to understand your use case a bit more.

**Comment by randyzwitch** [comment]
Closing this issue, as its unclear whether this needs a feature request or whether its solvable in the current product (I'm leaning towards the latter). If this is still an issue, please let me know and we'll figure out the next steps.
