### ISSUE TITLE
value overflow issue

### ISSUE THREAD

**Issue by titawork** [omnisci/omniscidb#354]
4.6.1 mapd with JDBC connector. 
My host computer. redhat 7.4.  X86_64 with 376G RAM, Tesla P100 with 16G graphics memory. 

When I execute  "select * from View3"
fatal error happen, the log as following,

E0605 07:55:25.975816 64016 ExecutionDispatch.cpp:159] Failed to allocate 15235361355721605120 bytes of memory
E0605 07:55:25.976677 60994 MapDHandler.cpp:4929] Exception: Not enough host memory to execute the query
E0605 07:57:26.585990 64058 ExecutionDispatch.cpp:159] Failed to allocate 15235361355721605120 bytes of memory
E0605 07:57:26.586272 60994 MapDHandler.cpp:4929] Exception: Not enough host memory to execute the query

When I set the test tables with 1,000,000 records. 2,000,000 records, no such error. 
Once with 10,0000,000, the error happen. I think it must be bug . 

I have some tables. 
table_x1           9,999,999 records
table_1            10,000,000 records
table_2            10,000,000 records
and other tables.

When I execute 
CREATE VIEW View1 AS SELECT 
table_x1.exchange_type,
table_x1.money_type,
table_x1.report_account,
table_x1.stock_code,
table_x1.csdc_stock_type,
table_x1.exbusin_kind,
table_x1.seat_no,
table_x1.trade_id,
table_x1.business_id,
table_x1.business_date,
table_x1.business_time,
table_x1.business_price,
table_x1.settle_price,
table_x1.settle_amount,
table_x1.business_balance,
table_x1.settle_balance,
table_x1.clear_balance,
table_x1.settle_date,
table_x1.return_code,
table_x1.business_remark,
table_x1.first_fare1,
table_x1.first_fare2,
table_x1.first_fare3,
table_x1.first_fare4,
table_x1.first_fare5,
table_x1.first_farex,
table_2.branch_no,
table_2.op_table_2_way as table_2_way,
table_2.report_time,
table_2.fare_kind,
table_2.table_2_type,
table_2.table_2_no,
table_2.room_code,
table_2.fund_account,
table_2.stock_account,
table_2.table_2_prop,
table_2.order_id,
table_2.table_2_bs,
table_2.business_amount,
table_1.fare_kind_str,
table_1.discount_model,
stkcode.stock_type,
stkcode.store_unit 
from table_x1,
table_2,
table_1,
stkcode,
allbranch,
seats 
where 
table_x1.seat_no=seats.seat_no and 
table_x1.table_2_bs =table_2.table_2_bs and 
table_x1.report_account=table_2.report_account and 
table_x1.stock_code=table_2.stock_code and 
table_x1.exchange_type=table_2.exchange_type and 
table_2.fund_account=table_1.fund_account and 
table_x1.stock_code=stkcode.stock_code and 
allbranch.branch_no=table_1.branch_no

get 9,999,999 records View1
and then

create view View2 as 
select 
reportaccount,
seatno,
orderid,
stockcode,
branchno,
entrusttype,
entrustbs,
storeunit, 
max(View1.businessdate) as entrustdate,
sum(businessamount * businessprice)/sum(businessamount) as businessprice,
sum(businessamount) as businessamount,
sum(businessbalance) as businessbalance,
sum(clearbalance) as clearbalance, 
sum(firstfare1) as fare1,
sum(firstfare2) as fare2,
sum(firstfare3) as fare3,
sum(firstfare4) as fare4,
sum(firstfare5) as fare5,
sum(firstfarex) as farex,
max(farekind) as farekind,
max(entrustno) as entrustno,
max(roomcode) as roomcode,
max(discountmodel) as discountmodel,
max(entrustway) as entrustway 
from View1 
group by reportaccount,seatno,orderid,stockcode,branchno,entrustbs,entrusttype,storeunit

got 9999999 records View2.

finially,
create view View3 as select reportaccount,
seatno,
orderid,
stockcode,
branchno,
entrusttype,
entrustbs,
storeunit, 
entrustdate,
businessprice,
businessamount,
businessbalance,
clearbalance, 
fare1,
fare2,
fare3,
fare4,
fare5,
farex,
farekind,
entrustno,
roomcode,
discountmodel,
entrustway, 
businessamount * storeunit as ppreamount,
fare1+fare2+fare3+farex as pprefare,
-1 * (businessbalance) - (fare1+fare2+fare3+farex) as ppreclearbalance,
4002 as pprebusinessflag,
0 as pprefrozenamount,
0 as pprecorrectamount,
-1 * businessamount as pprerealamount,
abs(clearbalance) as ppresumbuybalance,
abs(businessamount) as ppresumbuyamount,
abs(businessbalance) as pprecostbalance,
0 as ppresumsellbalance,
0 as ppresumsellamount,
0 as pprerealstatus,
50 as ppremaxfare 
from View2 
where entrustbs=1 
and entrusttype=0

got 9,999,999 records View3.

I can get the number by "select count(*) from view3."
but if I select * from view3, some fault happen.

**Comment by randyzwitch** [comment]
This isn't a bug per se, but rather a reflection of OmniSci as a columnar database. Your views are substantial relative to the small amount of GPU memory available. As the record count increases in the tables, you aren't able to keep all of the records in GPU memory at the same time, so you get the "cannot allocate memory" error message.

One possible thing to explore is whether the `allow-cpu-retry` configuration argument is set to TRUE. In the past, it has defaulted to FALSE, as we had users opt-in to the lower performance CPU retrying queries when the GPU ran out of memory. But because of questions like yours, and people expecting that there shouldn't be errors like this, we've since defaulted the value to TRUE. Now, when OmniSci estimates that the result can't be performed with the amount of GPU memory available, it will spill-over to using CPU memory.

https://www.omnisci.com/docs/latest/4_configuration.html

**Comment by cdessanti** [comment]
if you get an explain calcite you'll discover that the optimizer is trying to materialize every view used in the query, so the estimation of memory needed is huge, given the number of columns of your views.

you can try to set enable-calcite-view-optimize to true, restart the server and then retry your query.

But it's possible likely you are running out of memory because the server would need an insane amount of memory for the group by buffers

check into the logs if you have a message like that (they are on mapd_log subdirectory where you placed the data)

QueryMemoryInitializer:129 : group_buffer_size 5340956456173426688
E0609 17:50:22.960036 85572 ExecutionDispatch.cpp:159] Failed to allocate 5340956456173426688 bytes of memory

**Comment by asuhan** [comment]
@cdessanti @titawork Under no circumstances we would legitimately want to allocate 5340956456173426688 bytes of memory, let alone 15235361355721605120 bytes. This points to a bug, such numbers are many, many orders of magnitude off and deserves investigation. This table has 10M entries and no joins are involved as far as I can tell, there is no way we would legitimately need these amounts of memory!

Also: "if I select * from view3, some fault happen". What is this "some fault"?

**Comment by cdessanti** [comment]
@asuhan,

Yes,
 there is something wrong with cardinality estimation when the query is moved from GPU execution to CPU.
 
While the result of the estimation query is 31668028, the cardinality changes to 270314778748670208 when the execution is moved to CPU, causing the huge memory request

here an extract of omnisci_logfile
[huge_memory_request.txt](https://github.com/omnisci/omniscidb/files/3270752/huge_memory_request.txt)

**Comment by asuhan** [comment]
@alexbaden Can you take a look? This is an interesting bug.

**Comment by titawork** [comment]
> @cdessanti @titawork Under no circumstances we would legitimately want to allocate 5340956456173426688 bytes of memory, let alone 15235361355721605120 bytes. This points to a bug, such numbers are many, many orders of magnitude off and deserve investigation. This table has 10M entries and no joins are involved as far as I can tell, there is no way we would legitimately need these amounts of memory!
> 
> Also: "if I select * from view3, some fault happen". What is this "some fault"?

Thank you for your reply. The "some fault"  is the "Not enough host memory" problem.

E0605 07:55:25.975816 64016 ExecutionDispatch.cpp:159] Failed to allocate 15235361355721605120 bytes of memory
E0605 07:55:25.976677 60994 MapDHandler.cpp:4929] Exception: Not enough host memory to execute the query
E0605 07:57:26.585990 64058 ExecutionDispatch.cpp:159] Failed to allocate 15235361355721605120 bytes of memory
E0605 07:57:26.586272 60994 MapDHandler.cpp:4929] Exception: Not enough host memory to execute the query

**Comment by asuhan** [comment]
Phew, that's at least a clean exception, not a fault per-se. Still, our memory requirement is hilariously off.

**Comment by titawork** [comment]
This issue can be reproduced everytime in my situation. Now I am rebuild the enviroment for this test. If any infomation needed, tell me please.

**Comment by asuhan** [comment]
Could you share the scripts you use to generate the data? That'd help us quite a bit.

**Comment by titawork** [comment]
table_1 and table_2 are load from oracle.

table_2 script for oracle
declare 
  -- Local variables here
  i integer;
  V_iCount Integer := 0;
  V_iCount2 Integer := 0;
begin
    loop
      insert into table_2 (INITDATE,
                                   CURRDATE,
                                   CURRTIME, 
                                   ENTRUSTNO, 
                                   OPBRANCHNO, 
                                   OPERATORNO, 
                                   OPENTRUSTWAY, 
                                   OPSTATION,     
                                   BATCHNO, 
                                   BRANCHNO, 
                                   FUNDACCOUNT, 
                                   CLIENTID,   
                                   EXCHANGETYPE, 
                                   STOCKACCOUNT, 
                                   REPORTACCOUNT,
                                   SEATNO,
                                   STOCKCODE,
                                   STOCKTYPE, 
                                   ENTRUSTBS, 
                                   ENTRUSTAMOUNT, 
                                   ENTRUSTPRICE, 
                                   ENTRUSTTYPE, 
                                   ENTRUSTPROP, 
                                   REPORTTIME, 
                                   REPORTNO, 
                                   RECORDNO, 
                                   BUSINESSAMOUNT, 
                                   WITHDRAWAMOUNT, 
                                   BUSINESSPRICE, 
                                   BUSINESSBALANCE, 
                                   CLEARBALANCE, 
                                   PREVBALANCE, 
                                   REPORTBS, 
                                   STOREUNIT, 
                                   REPORTUNIT, 
                                   ERRORNO, 
                                   ENTRUSTSTATUS, 
                                   MONEYTYPE, 
                                   CLIENTGROUP, 
                                   ROOMCODE, 
                                   CANCELSERIALNO, 
                                   FAREKIND, 
                                   POSITIONSTR, 
                                   LOGINPBU, 
                                   ORDERID, 
                                   ORIGORDERID)
                           values (20190429,
                                   20190429,  
                                   152108226, 
                                   V_iCount,       
                                   8888,         
                                   '0',         
                                   '7',            
                                   'op_station_2', 
                                   V_iCount,     
                                   1,        
                                   '22' || lpad(to_char(V_iCount),7,'0'), 
                                   '22' || lpad(to_char(V_iCount),7,'0'), 
                                   '1',
                                   'C22' || lpad(to_char(V_iCount),7,'0'),
                                   'C22' || lpad(to_char(V_iCount),7,'0'),
                                   '17744',
                                   '600570',   
                                   '0',        
                                   '1',        
                                   1000.00,        
                                   16.0000, 
                                   '0', 
                                   '0', 
                                   0, 
                                   V_iCount, 
                                   0, 
                                   V_iCount, 
                                   0.00, 
                                   0.0000, 
                                   0.00, 
                                   0.00, 
                                   16085.00, 
                                   '1', 
                                   1, 
                                   1, 
                                   0, 
                                   '2', 
                                   '0', 
                                   1, 
                                   V_iCount, 
                                   'AS_CTRADE_BJ#0#10:53:16.320##440', 
                                   2201, 
                                   '2019042902152108226000220' || lpad(to_char(V_iCount),7,'0'), 
                                   ' ', 
                                   '' || V_iCount,
                                   '' || V_iCount);
    V_iCount := V_iCount + 1; 
    if V_iCount = 2000000 then
      commit;
      exit;
    end if; 
	V_iCount2 := V_iCount2 + 1; 
    if V_iCount2 = 5000 then
      commit;
      V_iCount2 := 0;
    end if;
  end loop;
  commit;
end;

table_1 script for oracle:
declare 
  -- Local variables here
  i integer;
  V_iCount Integer := 0;
  V_iCount2 Integer := 0;
begin
    loop
      insert into table_1 (BRANCHNO, CLIENTID, FUNDACCOUNT, FUNDCARD, MAINFLAG, RISKLEVEL, RISKENDDATE, INTERACCOUNT, CLIENTGROUP, ROOMCODE, ASSETPROP, FAREKINDSTR, DISCOUNTMODEL, ENENTRUSTWAY, CLIENTRIGHTS, RESTRICTION, PROFITFLAG, OPENDATE, CANCELDATE, PRODUCTFLAG, FUNDACCTSTATUS, LIMITFLAG, REMARK, POSITIONSTR)
      values (0, ' ', '22' || lpad(to_char(V_iCount),7,'0'), ' ', ' ', 0, 20190527, ' ', 0, 0, '0', ' ', 0, ' ', ' ', ' ', ' ', 20190527, 20190527, ' ', ' ', 0, ' ', '22' || lpad(to_char(V_iCount),7,'0'));
    V_iCount := V_iCount + 1; 
    if V_iCount = 1000000 then
      commit;
      exit;
    end if; 
	V_iCount2 := V_iCount2 + 1; 
    if V_iCount2 = 5000 then
      commit;
      V_iCount2 := 0;
    end if; 
  end loop;
  commit;
end;

table_x1 load from two csv files. Each file contains 5,000,000 record. Acturally 9,999,999 records loaded.
I will confirm the amount of records in these two files.
