### ISSUE TITLE
[BUG?] Casting integer to another integer type always returns SMALLINT value.

### ISSUE THREAD

**Issue by pearu** [omnisci/omniscidb#359]
The type of `CAST(1 AS INT)` is `SMALLINT` while expecting `INTEGER`.
Similarly, `CAST(1 AS TINYINT)` and  `CAST(1 AS BIGINT)` return a value of type `SMALLINT`.

**Comment by pearu** [comment]
As a fix, in `RelAlgTranslator::translateLiteral` method change the line
```
return scale && lit_ti != target_ti ? lit_expr->add_cast(target_ti) : lit_expr;
```
to
```
return lit_ti != target_ti ? lit_expr->add_cast(target_ti) : lit_expr;
```

**Comment by asuhan** [comment]
Fixed by https://github.com/omnisci/omniscidb/commit/c9c60cb193230827993d08756fde033b4aed5295.
