### ISSUE TITLE
Different default Parameter of copy command for exporting and loading data 

### ISSUE THREAD

**Issue by titawork** [omnisci/omniscidb#362]
Such as table test1,
t1|t2|t3
1|2|3
3|3|4
5|4|5
7|5|6
step 1:
copy (select * from test1) to '/home/omnisci/data/test.csv';
we got 4 records in test.csv

step2:
truncate table test1;

step3:
copy test1 from '/home/omnisci/data/test.csv';
we got 3 records.

The problem is when copy table to csv the default "header = 'false";
But when load data from csv, the default "header = 'true'"
So the first line is traded as the head.
It is not a big issue. But it will puzzle the users.

**Comment by randyzwitch** [comment]
I think this is the case where there's no substitute for reading the documentation. Regardless of how we set the parameter flag, some users would expect the opposite behavior.
