### ISSUE TITLE
add window function for analyze

### ISSUE THREAD

**Issue by cmdares** [omnisci/omniscidb#364]
row_number()over(partition by order by )
...
Lag/lead/first_value....

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by randyzwitch** [comment]
In OmniSci 4.7, preliminary support for window functions was added. Because of the usefulness of this functionality, we will continue to improve it in future releases. 

> OmniSciDB now supports Window functions. Empty Window function partitions are currently not supported; that is, all Window functions must include a PARTITION BY key in the OVER clause. Also, OmniSci recommends that you use Window functions over aggregate query outputs at this time (instead of raw data). Future releases aim to improve scale and performance and remove these restrictions; see the documentation for details on what is supported.

https://www.omnisci.com/docs/latest/7_0_release.html#4-7-0-released-june-13-2019
