### ISSUE TITLE
BUG: Function IS TRUE not supported

### ISSUE THREAD

**Issue by xmnlab** [omnisci/omniscidb#375]
hey everyone!

I am trying to run this query: 

```sql
SELECT count(CASE WHEN "string_col" IN ('1', '7') THEN "bool_col" ELSE NULL END) AS "count" FROM functional_alltypes
```

but it raises this error:  `Function IS TRUE not supported `

if I change `bool_col' to another kind of columns, example `int_col`, it works.

if i just run `SELECT count("bool_col") AS "count" FROM functional_alltypes` it works

Using `EXPLAIN CALCITE` it shows:

```
LogicalAggregate(group=[{}], count=[COUNT($0)])
  LogicalProject($f0=[OR(AND(IS TRUE(OR(=($11, '1'), =($11, '7'))), $3), AND(null, IS NOT TRUE(OR(=($11, '1'), =($11, '7')))))])
    EnumerableTableScan(table=[[ibis_testing, functional_alltypes]])
```

**Comment by alexbaden** [comment]
Thanks! We'll take a look, it is likely this is new Calcite syntax we need to support.

**Comment by xmnlab** [comment]
omniscidb version 4.7.0-20190614-4559864637

**Comment by alexbaden** [comment]
Fixed with https://github.com/omnisci/omniscidb/commit/b57dfe4b9f9d0517efd7d3fb657e4190cd0db4e9

**Comment by xmnlab** [comment]
thanks!
