### ISSUE TITLE
Docker, where to download omnisci-latest-Linux-x86_64.tar.gz

### ISSUE THREAD

**Issue by littleforce163** [omnisci/omniscidb#379]
Hello, I'd like to build an image from dockerfile, where can I get the file omnisci-latest-Linux-x86_64.tar.gz? Please give a site link.

**Comment by randyzwitch** [comment]
The links for downloads are in the README:

https://github.com/omnisci/omniscidb#pre-built-binaries-for-linux-for-stable-releases-of-the-project

**Comment by cdessanti** [comment]
If you were asking a link to a guide to install a docker image the recipes are in the main site

https://docs.omnisci.com/latest/4_docker.html

**Comment by littleforce163** [comment]
Hi Randyzwitch,
Do you mean https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cuda.tar.gz?
They are not the same file name. Shall I rename?

**Comment by littleforce163** [comment]
Hi cdessanti,
I'd like to build a docker image from dockerfile, but not find the needed tar ball.

**Comment by randyzwitch** [comment]
@littleforce163 If I'm seeing it correctly, the only difference in the naming appears to be the addition of the choice of `-cuda` or `-cpu`. In that case, you pick the version you need, GPU or CPU-only respectively.
