### ISSUE TITLE
How to create auto increment id field?

### ISSUE THREAD

**Issue by YanzheL** [omnisci/omniscidb#426]
I want to define an auto increment ID field, just like the primary id in mysql.
Is that possible?
If not, how can I simulate this pattern? I need to have a unique ID of each row in table.

**Comment by cdessanti** [comment]
You can use the system column called rowid. it is a bigint datatype column that starts at 0.
But unloading and reloading the table data a different rowid could be assigned to the previous row content

**Comment by YanzheL** [comment]
Understood, thanks.
