### ISSUE TITLE
Get the actual encoding value of DICT encoded TEXT

### ISSUE THREAD

**Issue by YanzheL** [omnisci/omniscidb#428]
If a field has the type of `TEXT ENCODING DICT(32)`, how can I get the actual 32-bit encoding value?
Is there a built-in function for extracting this info?

Since this encoding is an integer index in the dictionary of this TEXT field, it's useful to extract the encoding as an ID of this string to be used in external systems.

Is the encoding (or index) a zero-based auto-increment value, or just a random hash?

**Comment by randyzwitch** [comment]
Hi @YanzheL - 

I believe you can use `key_for_string(string_column)` to get the integer value from a TEXT ENCODING DICT column.

Best,
Randy

**Comment by YanzheL** [comment]
Thanks.
Is `key_for_string` a built-in SQL function? I didn't see it in your [Official Documentation](http://docs.omnisci.com/)

**Comment by randyzwitch** [comment]
I think it's probably just an omission in our docs.
