### ISSUE TITLE
How to save registered UDFs

### ISSUE THREAD

**Issue by YanzheL** [omnisci/omniscidb#453]
OmnisciDB 5.0.0 added support for Runtime UDFs.

The [Remote Backend Compiler Documentation](https://www.google.com/url?q=https://github.com/xnd-project/rbc&sa=D&ust=1573766976450000&usg=AFQjCNFvW1PPa2Q4qysiHWckTxkxoUNV7Q)
only said how to register UDFs at runtime, without saying how to save/persistent the registered UDF.

I want to register UDFs via python, and reuse them across server restart, and shared it to multiple clients (JDBC), so is there some way to save UDFs to config files?

Is the registered runtime UDFs visible at system scope, or just the session scope?

If persistent UDF is not supported, how can I add compiler-time UDFs?

**Comment by randyzwitch** [comment]
Yes, the UDF functionality via Python is runtime-only, not a permanent way to add functions to OmniSciDB. The original intent of the feature is more exploratory in nature, as opposed to a permanent/production use case as it seems like you are describing.

If you want to permanently add your own functions to OmniSci at compile time, you need to write the code in C++. Our documentation briefly covers this, but if you have a specific question about how to do this, please open another issue and we'd be happy to walk you through the process.

https://docs.omnisci.com/latest/5_math.html#user-defined-functions
