### ISSUE TITLE
about dump/restore db

### ISSUE THREAD

**Issue by ggcking** [omnisci/omniscidb#455]
"Added support for binary dump/restore of database tables."
how to do this ?

**Comment by cdessanti** [comment]
Hi @ggcking ,

the syntax to dump/ restore a table resembles the copy's one.

dump table table_name to '/path_of_backup/backup_file_name' with (compression='none|gzip|lz4');
restore table table_name from '/path_of_backup/backup_file_name' with (compression='none|gzip|lz4');

the default compression is gzip, and to use the lz4 (that's faster), you have to install the liblz4-tool.

at the time of writing, you can't overwrite an existing table with restore command, so if needed you have to drop it before the restore.

anyway we discussed this topic in the community forum (I did also a brief benchmark)

check this link [ https://community.omnisci.com/communities/community-home/digestviewer/viewthread?GroupId=13&MessageKey=23a8ec50-09eb-405a-b05f-502dde489f35&CommunityKey=d06df790-8ca4-4e54-91a0-244af0228ddc&tab=digestviewer&ReturnUrl=%2fhome](url)

**Comment by randyzwitch** [comment]
The documentation is also at this link: https://docs.omnisci.com/latest/5_tables.html#dump-table
