### ISSUE TITLE
Exception: Non-empty LogicalValues not supported yet

### ISSUE THREAD

**Issue by gshimansky** [omnisci/omniscidb#461]
16 tests in Ibis project (https://github.com/ibis-project/ibis) are marked as Skip for OmnisciDB backend because they produce exception `E 77661 MapDHandler.cpp:5080 Exception: Non-empty LogicalValues not supported yet`. Examples of such statements are following:

```
omnisql> SELECT coalesce(5, NULL, 4) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT abs(-5) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT ceil(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT floor(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT exp(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT CAST(sign(5.556) AS double) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT CAST(sign(0) AS tinyint) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT sqrt(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT ln(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT log10(5.556) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT mod(11, 3) AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql> SELECT now() AS tmp;
Exception: Non-empty LogicalValues not supported yet
omnisql>
```

**Comment by gshimansky** [comment]
Statement `SELECT nullif(10, 5) AS tmp;` causes the same exception.

**Comment by randyzwitch** [comment]
I believe all of these are caused because we require a table name to be specified in a query. The exception could be clearer.

**Comment by alexbaden** [comment]
Yes, we currently don't support statements without a table attached to the query. In other words:
```
SELECT nullif(10, 5) AS tmp FROM t;
```
would likely work fine.

I haven't looked too deeply into how we would evaluate these queries yet, but it would probably require some changes in the execution paths to remove the assumption of an input table being required.

**Comment by gshimansky** [comment]
You can right, adding any existing table name to the statement allows it to execute normally.
