### ISSUE TITLE
How to run in jit debug mode?

### ISSUE THREAD

**Issue by Wen-He** [omnisci/omniscidb#462]
The output of command `./bin/omnisci_server -h` only shows options in `help_desc`. How could I list and set options in `developer_desc`?
I followed the description of `jit-debug-ir` option  in `developer_desc`, turn off the `ENABLE_JIT_DEBUG` build flag and run with `-jit-debug-ir` option. But nothing generated in dir `/tmp`. 
``` 
developer_desc.add_options()(
    "jit-debug-ir",
    po::value<bool>(&jit_debug)->default_value(jit_debug)->implicit_value(true),
    "Enable runtime debugger support for the JIT. Note that this flag is "
    "incompatible "
    "with the `ENABLE_JIT_DEBUG` build flag. The generated code can be found at "
    "`/tmp/mapdquery`.");
```

**Comment by cdessanti** [comment]
./bin/omnisci_server --dev-option to get all hidden options

the option you are looking for is this one

```
  --jit-debug-ir [=arg(=1)] (=0)        Enable runtime debugger support for the
                                        JIT. Note that this flag is
                                        incompatible with the
                                        `ENABLE_JIT_DEBUG` build flag. The
                                        generated code can be found at
                                        `/tmp/mapdquery`.
```

**Comment by Wen-He** [comment]
According to the option's description, I turned off the `ENABLE_JIT_DEBUG` build flag and ran with `./bin/omnisci_server --jit-debug-ir=1`.
But nothing generated in dir `/tmp`. The file `mapdquery` dosen't exist in dir `/tmp` as expected.

**Comment by ienkovich** [comment]
This flag seems to be broken or deprecated right now. You can use --log-channels flag to dump generated code into log channels IR and PTX.
