### ISSUE TITLE
SQL function TO_DATE is not implemented

### ISSUE THREAD

**Issue by gshimansky** [omnisci/omniscidb#476]
The following code results in exception
```
CREATE TABLE table4 (
timestamp_col TIMESTAMP(0));
SELECT to_date("timestamp_col") BETWEEN toDate('2014-12-01') AND toDate('2017-01-05') AS tmp FROM table4;
```
`Exception: Exception occurred: org.apache.calcite.runtime.CalciteContextException: From line 1, column 8 to line 1, column 33: No match found for function signature to_date(<TIMESTAMP>)`

Ibis tests `test_date_scalar_parameter`, `test_date_extract` and `test_date_truncate` fail because of this.

**Comment by cdessanti** [comment]
Hi,

you can use DATE or CAST as DATE (the same is true with timestamp) with literals, and cast as date with fields

```
select cast(PosTimeDate as date) between **date** '2014-12-01' and **date** '2015-01-01' from table4;
or
select cast(PosTimeDate as date) between cast( '2014-12-01' as date) and cast('2017-01-07' as date) from table4;

```

**Comment by gshimansky** [comment]
Thanks for letting me know. In this case it is necessary to change Ibis to generate such code for the corresponding operation.
