### ISSUE TITLE
Can I run omniscidb on PC?

### ISSUE THREAD

**Issue by achimbab** [omnisci/omniscidb#495]
Hello, 

I am new in the omniscidb and have a basic question.

Is it possible to run the omniscidb on my PC for test?

The below is hardware specifications of my PC.
```
CPU : i7-9 9700K (x86)
GPU : NVIDIA RTX 2070 (turing architecture)
HDD : SAMSUNG 970 EVO Plus M.2 2280 (1TB)
RAM : 64GB
```

Thank you.

**Comment by asuhan** [comment]
Hello @achimbab ,

As long as you're running a recent Linux distribution, yes.

**Comment by achimbab** [comment]
@asuhan 
Thank you :)
