### ISSUE TITLE
Omnisci in AWS issues

### ISSUE THREAD

**Issue by archenroot** [omnisci/omniscidb#499]
I have a set of issues which I noticed on just now created omnisci instance in AWS.

Login issues:
1. Minor - you state in your instructions to use user mapd while the system autofill admin user
2. Minor (but the info is not available from AWS instance instructions) - the UI autofill omnisci database name, while this will fail on not exist, so I tried mapd and it worked.

Performance issues:
with predefined g4dn.4xlarge which is running, I am not sure if I pickup Shared/Dedicated/Dedicated Host deployment, but when playing with 3 preloaded datasets even very small (few milions), the experience is not milisecond, but more second based (2-8 second refresh)

I am creating short video footage from my AWS instance and will share here links. I already tested omnisci on DGX-1 back in time, it was really fast, so not sure what is happening here. I also think about creating custom ec2 gpu instance and install omnisci trial manually or via docker.

**Comment by archenroot** [comment]
this is not that bad - https://youtu.be/16c8uTGHhBs

but I will do more videos.

**Comment by archenroot** [comment]
So, I did some tests and actually the flights demo is quite fast on 7M records operations, what is really slow is geographical map in NYC Tree Census 2015 dashboard, the data set is about those 700k records, the geo map updates taking from 2 to 5 seconds at moment... other data only dashboards (no map) refresh also quite fast, so I think it could be specific issue to this dashboard and type of data combination probably.

**Comment by alexbaden** [comment]
Hi @archenroot 

Thanks for this -- I've forwarded your concerns on to our product team and will let you know when I hear back. It does appear that the rendering performance on the g4dn is not up to our usual standards. If you still have the server INFO log I would be interested in seeing it, but we will also do some investigating on our end.

**Comment by archenroot** [comment]
@alexbaden - thx for feedback, I am afraid if the issue is also not on low performance client, I have tested on workstation and it worked better. Still I will report back during also builds on custom data.

**Comment by archenroot** [comment]
I played today a bit with omnisci again and I loaded some our custom data which are even bigger than example datasets, but without geo and it was fast, I think there is something slow with mapbox dashboard, but in the morning it was fast, right now on our demo instance it is again slow. I will get tomorrow all log files from instance and share.....

**Comment by archenroot** [comment]
I got today new laptop and actually I must admit that all performance issues are gone, it seems like mapbox dashboard has some performance requirements on the client side, the original device i used to test was under some constant (50%...) load and this probably caused the slow omnisci responses... 

closing as not a bug...
