### ISSUE TITLE
UDF Clang Compile Issue

### ISSUE THREAD

**Issue by RobAShear** [omnisci/omniscidb#505]
I'm trying to insert the boilercode from example page: "https://docs.omnisci.com/latest/5_math.html#user-defined-functions" and I am receiving this issue. I have only copy and pasted the code my udf directory. When restarting omnisci_server I receive this issue:

concat.cpp:2:59: error: token is not a valid binary operator in a preprocessor subexpression
#if defined(clang) && defined(CUDA) && defined(CUDA_ARCH) #define DEVICE device #else #define DEVICE #endif                                                                   ^
                                                                 ~~~~~~~~~~~~~~~~~~ ^
concat.cpp:4:2: error: unterminated conditional directive
#if defined(clang) && defined(CUDA) && defined(CUDA_ARCH) #define ALWAYS_INLINE #else #define ALWAYS_INLINE attribute((always_inline)) #endif
 ^
concat.cpp:3:2: error: unterminated conditional directive
#if defined(clang) && defined(CUDA) && defined(CUDA_ARCH) #define NEVER_INLINE #else #define NEVER_INLINE attribute((noinline)) #endif
 ^
concat.cpp:2:2: error: unterminated conditional directive
#if defined(clang) && defined(CUDA) && defined(CUDA_ARCH) #define DEVICE device #else #define DEVICE #endif
 ^
4 errors generated.


What is the best approach for fixing this error? **Thank you so much for any help!**

**Comment by alexbaden** [comment]
Hi @RobAShear ,

Thanks for flagging. It looks like there might be some formatting problems in the docs. 

We recently introduced an `OmniSciTypes.h` file to hold all that boilerplate for you. If you are using the OS edition, you can find it in your build directory.. but it should be relatively backwards compatible. The file is here: 
https://github.com/omnisci/omniscidb/blob/master/QueryEngine/OmniSciTypes.h

You will also need this helper header: https://github.com/omnisci/omniscidb/blob/master/Shared/funcannotations.h

If you are building from source, both files will be copied to the build dir, and you can simply include `build/QueryEngine/OmniSciTypes.h`. Let me know if that helps!

**Comment by RobAShear** [comment]
> Hi @RobAShear ,
> 
> Thanks for flagging. It looks like there might be some formatting problems in the docs.
> 
> We recently introduced an `OmniSciTypes.h` file to hold all that boilerplate for you. If you are using the OS edition, you can find it in your build directory.. but it should be relatively backwards compatible. The file is here:
> https://github.com/omnisci/omniscidb/blob/master/QueryEngine/OmniSciTypes.h
> 
> You will also need this helper header: https://github.com/omnisci/omniscidb/blob/master/Shared/funcannotations.h
> 
> If you are building from source, both files will be copied to the build dir, and you can simply include `build/QueryEngine/OmniSciTypes.h`. Let me know if that helps!

Thank you for the header files! I ran into another issue after including them. Let me know what I'm doing wrong. Early morning with lots of brain farts already!


File looks as such:

```
#include <cstdint>
#include "/opt/omnisci/QueryEngine/OmniSciTypes.h"

EXTENSION_NOINLINE int32_t udf_diff(const int32_t x, const int32_t y) { return x - y; }
```

**error message returned is:**
```
error: unknown argument: '-faddrsig'
MapDHandler.cpp:272 Failed to initialize UDF compiler: LLVM IR ParseError: /var/lib/omnisci/udf/concat_cpu.bc: /var/lib/omnisci/udf/concat_cpu.bc: Could not open input file: No such file or directory
```

**Comment by alexbaden** [comment]
Ah, I've seen that before -- typically is a problem with your `clang` version. Can you check `clang -v`?

**Comment by RobAShear** [comment]
@alexbaden It looks like I have two installed. Clang 6.0 and clang 9.0.

**Comment by RobAShear** [comment]
@alexbaden I got it to work finally. Your header file worked. I had to remove clang 6.0 and make clang++ point to clang++-9 for it to compile. Now is trying to figure out how to use the udf allowed data types!
