### ISSUE TITLE
FSI: Migrate from arrow 0.13 to arrow 0.15.1

### ISSUE THREAD

**Issue by fexolm** [omnisci/omniscidb#508]
In arrow 0.13 CSV reader doesn't support headerless CSV. Also, it is a bit slower than new version.

**Comment by aregm** [comment]
@alexbaden Is this already merged?

**Comment by ognone** [comment]
Is this related to
```
./mapd-core/DataMgr/ForeignStorage/ArrowCsvForeignStorage.cpp:20:10: fatal error: arrow/csv/column-builder.h: No such file or directory
   20 | #include <arrow/csv/column-builder.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fexolm** [comment]
@ognone you may just replace it with column_builder (with underscore) for arrow 0.15

**Comment by fexolm** [comment]
@ognone not at all, arrow 0.15 breaks backward compatibility in some places. So all code which uses old APIs should be replaced.
