### ISSUE TITLE
what is the price of community version fee?

### ISSUE THREAD

**Issue by ggcking** [omnisci/omniscidb#517]

**Comment by randyzwitch** [comment]
Hi @ggcking - 

When Community Edition was available, it was for users to experience the power of OmniSciDB and  Immerse, but for non-commercial purposes. It was never intended for commercial users to use as a development environment, or for use in a commercial setting as long as it didn't make money. As such, we provided this for free, but given the confusing nature of the license, we have stopped providing Community Edition.

For users to try the current OmniSci platform, we have a 14-day free trial of [OmniSci Cloud](https://www.omnisci.com/cloud). If you do not need Immerse, but just fast SQL queries, you can use OmniSciDB under its Apache 2.0 license for free in any manner provided by that license. Finally, if you need Immerse along with OmniSciDB, you can license OmniSci Enterprise Edition. To get a pricing quote, please contact our sales team at sales@omnisci.com, or feel free to contact me at randy.zwitch@omnisci.com and I'd be happy to make an introduction for you.

Best,
Randy
