### ISSUE TITLE
Documentation: SQImporter for BigQuery

### ISSUE THREAD

**Issue by mishig25** [omnisci/omniscidb#532]
Does the latest doc about SQLIMporter (https://docs.omnisci.com/latest/6_loading_data.html) contain up to date information about loading data from Big Query? Also, is there any other documentation where I can get more comprehensive info/tutorial about loading data from Big Query?
Thanks a lot!

**Comment by randyzwitch** [comment]
HI @mishig25 - 

The BigQuery code should be correct, with the caveat that you'll need to make sure the paths are correct. But in general, SQLImporter relies heavily on JDBC, so there shouldn't be much that can go wrong. If you find that it doesn't work, please let us know and we'll help you work through the issue.

We don't have a more comprehensive tutorial on BigQuery, is there a specific area that you need help with?

Best,
Randy

**Comment by mishig25** [comment]
Hi @randyzwitch! Thank you very much for the reply.
I'd like to import entirety of one of my big query tables into an omnisci table.
Let's day that my table id is: testproject:testdataset.mytable and my omnisci table: mytable

With the above information, could you please help me construct the bigquery sqlimporter command? Thanks a lot!

**Comment by mishig25** [comment]
Where do I find: /opt/omnisci/bin/omnisci-1.0-SNAPSHOT-jar-with-dependencies-BQ.jar
When I run:  /opt/omnisci$ find . -name *.jar
I get those:
./bin/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar
./bin/omnisci-jdbc-5.1.2.jar
./bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by cdessanti** [comment]
> 
> 
> Where do I find: /opt/omnisci/bin/omnisci-1.0-SNAPSHOT-jar-with-dependencies-BQ.jar
> When I run: /opt/omnisci$ find . -name *.jar
> I get those:
> ./bin/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar
> ./bin/omnisci-jdbc-5.1.2.jar
> ./bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar
> 
> Version I'm using: OmniSci Server Version: 5.1.2-20200304-e118922084

I would give a try to mapd-1.0-SNAPSHOT-jar-with-dependencies.jar

I tried to find a Big Query jar in the previous releases, but I didin't find out

**Comment by mishig25** [comment]
Really like the OmnisciDB project. However, lack of clear documentation on how to load data is a big bottleneck for newcomers like me. I really hope that OmnisciDB gets better documentation on how to load data

**Comment by randyzwitch** [comment]
Thanks for the feedback @mishig25. We're certainly trying to make the documentation as best as it can be, but unfortunately due to the pace of change in the project, the docs get out of date. But now that I know there is a problem with BigQuery, we'll do our best to improve the example.

Best,
Randy
