### ISSUE TITLE
Build system tries to use bisonpp even when it's not found

### ISSUE THREAD

**Issue by eyalroz** [omnisci/omniscidb#590]
I'm trying to build OmniSciDB On my system (Devuan Beowulf, the same as Debian buster but without systemd).

The CMake invocation says it has found `bison++`, but the `CMakeCache.txt` has:
```
BISONPP_EXECUTABLE:FILEPATH=BISONPP_EXECUTABLE-NOTFOUND
```

Now, when I try to actually build, there's an attempt to actually invoke that not-found executable, and I get:
```
/bin/sh: 1: BISONPP_EXECUTABLE-NOTFOUND: not found
```

As a side-note - bison++ is very old, and I've been told bison itself supports C++ these days, so you guys should probably just depend on bison.

**Comment by alexbaden** [comment]
Thanks for the report @eyalroz . We have had some cross-platform issues with bison++ and are actually in the process of moving our DDL parsing into Calcite (our SQL parsing is also currently in Calcite), so we can remove bison++/flex++ as dependencies and use one framework for parsing. This has the nice side effect of creating one parser API, so you could imagine swapping Calcite for some other package as long as the same (or similar) output was generated. 

On Debian/Debian-like systems you might be able to use our prebuilt deps script for ubuntu to get around some of these issues -- have you tried `scripts/mapd-deps-prebuilt`? You will have to adjust the script to not do the OS checking to make sure you are on ubuntu. @andrewseidl probably has some other ideas to try.

**Comment by andrewseidl** [comment]
Alternatively try running `scripts/mapd-deps-ubuntu.sh` to install and build the dependencies, and feel free to let us know if there are any missing packages or naming differences between Ubuntu and Devuan/Debian.

In the meantime I've pushed a potential fix for the specific issue of cmake not properly handling bison++ (and flex++) not being installed.

**Comment by eyalroz** [comment]
@andrewseidl : "I've pushed" - so, I should try the andrew/590 branch?

**Comment by andrewseidl** [comment]
Sorry. Yes, please try that. The PR with the changes is https://github.com/omnisci/omniscidb/pull/594/files?w=1

**Comment by eyalroz** [comment]
So, the `mapd-deps-ubuntu.sh` is somewhat of a dangerous script in that it changes your system's default compiler. That's rather inappropriate. It could use the `CXX` and `CC` environment variables, or change the path to a directory where gcc and g++ link to another version etc.

Anyway, running it, I get to this point:
```
... etc etc ...
+ mkdir -p llvm-9.0.1.src/tools/clang/tools
+ mv clang-tools-extra-9.0.1.src llvm-9.0.1.src/tools/clang/tools/extra
+ pushd llvm-9.0.1.src/projects/
~/src/omniscidb/llvm-9.0.1.src/projects ~/src/omniscidb
+ patch -p0
patch: **** Only garbage was found in the patch input.
```
