### ISSUE TITLE
Explain `Hash join failed, No equijoin expression found for outer join`

### ISSUE THREAD

**Issue by ArthurTu** [omnisci/omniscidb#600]
https://github.com/omnisci/omniscidb/blob/1241207f20a0726ef5c33a08a8cf1f824ae01b95/QueryEngine/IRCodegen.cpp#L500

`select * from a join b on a.colx=b.colx and a.coly=b.coly`
works fine.

`select * from a left join b on a.colx=b.colx and a.coly=b.coly`
throws exception
`Exception: Hash join failed, reason(s): No equijoin expression found for outer join | Cannot fall back to loop join for non-trivial inner table size`.

colx is of type `DATE ENCODING DAYS(32)` while coly is of type `TEXT`.

What does this mean? What can I do to fix this?

**Comment by alexbaden** [comment]
Hi @ArthurTu . We currently do not support hash joins over a left/outer join with multiple join conditions. We need to make some changes to the left hand side code generation to ensure we don't let duplicate, non-matching rows through in the outer join case. We are able to fall back to loop joins, though the performance of loop joins decreases dramatically with increases in either lhs or rhs size. You can allow loop joins using the `allow-loop-joins` configuration parameter (`--allow-loop-joins` on the command line) or by increasing the value of `trivial-loop-join-threshold` to be greater than or equal to the number of rows in your inner table. By default this value is set to 1,000.

**Comment by ArthurTu** [comment]
Got it. Thank you for fast response :) I am closing the issue.

> We need to make some changes to the left hand side code generation to ensure we don't let duplicate, non-matching rows through in the outer join case.

BTW, is there any schedule for this?
