### ISSUE TITLE
Date error in docs?

### ISSUE THREAD

**Issue by dhirschfeld** [omnisci/omniscidb#618]
![image](https://user-images.githubusercontent.com/881019/105444613-e542d680-5cb9-11eb-9a24-1e8b28175d1a.png)

**Comment by cdessanti** [comment]
Hi @dhirschfeld,

Thanks for pointing that out; I checked this morning into official documentation, and the date is January 7, 2021

So maybe someone corrected the year in the date, but to make be sure, are you referring to this link?

https://docs.omnisci.com/overview/release-notes

**Comment by dhirschfeld** [comment]
That's the link. Looks like it's corrected now!
