### ISSUE TITLE
Linux-distro independent build toolchain

### ISSUE THREAD

**Issue by wesm** [omnisci/omniscidb#64]
I'm following the build instructions on Ubuntu 14.04. The diversity of system toolchains I find is a recipe for brittleness when it comes to developing something like a database with a lot of dependencies. Many Linux packages aren't built with -fPIC, for example.

In the Impala project, they developed a fully self-contained build toolchain (outside stable dependencies like autotools) so that any reasonable Linux is able to produce identical builds with all dependencies statically linked: https://github.com/cloudera/native-toolchain. So you could be on Ubuntu 12.04 through 17.04 and not run into any rough edges with old dependencies. This constraint forces you to pin every dependency, and by controlling all of the build flags up and down the toolchain you can easily create builds with no shared library dependencies. Maybe you are already doing this someplace. 

It might take some time (and some CMake modules aren't set up out of the box to pick up non-system versions of some libraries), but it would make MapD development more accessible for outsiders. 

I'll post more granular issues for any problems I may run into

**Comment by asuhan** [comment]
We have prebuilt dependencies per https://github.com/mapd/mapd-core#dependencies. Not sure about ABI compatibility with other distros (FIPS? glibc symbol versions?), but they worked at some point on Ubuntu as well, so it's a starting point.

@andrewseidl Have we tried to just use one version of the dependencies at least for our internal CentOS and Ubuntu builds and see how it goes? If we build them on CentOS 6 and tweak the flags properly, I believe we can get an universal version (or maybe two, FIPS and non-FIPS) for all recent distributions.

**Comment by wesm** [comment]
Are those pre-built dependencies posted online someplace to download? One approach is to build these with RedHat devtoolset-3 or 4 on CentOS 6 to avoid glibc and libstdc++ problems

**Comment by asuhan** [comment]
Yes: `https://internal-dependencies.mapd.com/mapd-deps/mapd-deps-latest.tar.xz`, per the `https://internal-dependencies.mapd.com/mapd-deps/deploy.sh` mentioned in the readme. Indeed, using devtoolset on CentOS 6 would be the safest bet for a binary compatible set of dependencies.

**Comment by randyzwitch** [comment]
@asuhan Do you have a feeling on how difficult it would be to do? Feels like a dozen remaining issues in this repo are around subtle differences in the build scripts, would be great to clean this up once and for all

**Comment by andrewseidl** [comment]
Easiest (and what we've been planning on doing) is to write some wrapper scripts around the Dockerfile at https://github.com/mapd/mapd-core/blob/master/docker/build/centos7/Dockerfile (that's exactly what we use on some of the build machines that generate the Community and Enterprise Editions).

Example usage is at: https://github.com/mapd/mapd-core/issues/254#issuecomment-410272482

**Comment by randyzwitch** [comment]
Closing this issue, as I feel like we're at a place where the project reasonably builds with a handful of commands and the `/omniscidb/scripts/mapd-deps-prebuilt.sh` script.
