### ISSUE TITLE
Casting a value to TINYINT does not work when using SQLImporter

### ISSUE THREAD

**Issue by georgikoemdzhiev** [omnisci/omniscidb#661]
Hello,

I am trying to do the following import:

Denodo database table A contains column1 with type set to **DECIMAL**

I have created a table A in omnisci using this SQL script:

```
CREATE TABLE A(
column1 TINYINT
);
```

I am using this SQL script with the `omnisql` utility:

```
SELECT cast(column1323 as TINYINT) as column1 from denododb
```

I am getting this error:

```
2021-06-22 16:28:34 INFO  SQLImporter:executeQuery:352 - Connecting to database url :jdbc:vdb://denododb.com:9999/?queryTimeout=3600000
2021-06-22 16:28:35 ERROR SQLImporter:executeQuery:464 - SQLException - java.sql.SQLException: Syntax error: Exception parsing query near 'TINYINT'
java.sql.SQLException: Syntax error: Exception parsing query near 'TINYINT'
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.generateSQLException(DAOVDBProxy.java:485)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.executeDeferred(DAOVDBProxy.java:467)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.executeDeferred(DAOVDBProxy.java:389)
        at com.denodo.vdb.jdbcdriver.VDBJDBCStatement.executeQuery(VDBJDBCStatement.java:335)
        at com.mapd.utility.SQLImporter.executeQuery(SQLImporter.java:383)
        at com.mapd.utility.SQLImporter.doWork(SQLImporter.java:341)
        at com.mapd.utility.SQLImporter.main(SQLImporter.java:326)
```

**Note**: if I change the type of column1 in the create script to `DECIMAL(1,0)` and the cast to:

```
SELECT cast(column1323 as DECIMAL(1,0)) as column1 from denododb
```

The import works fine.

**Comment by cdessanti** [comment]
Hi @georgikoemdzhiev 

The SQLImporter utility connects to the source database, runs the query, and inserts data into the Omnisci database (creating the target table with inferred datatypes if it doesn't exist).
If you specify a query that can't run in the source, you get this kind of error.

Checking the denodo documentation, it looks like it doesn't support the tinyint data type, but it's able to cast from SMALLINT, and for this reason, the first query failed, while the second worked.

Anyway, OmnisciDB supports decimals too, and you can use multiple encoding to save space (from 16 to 64 bits)
use this link as a reference for datatypes you can use with OmnisciDB on 5.6 Release

https://docs.omnisci.com/sql/data-definition-ddl/tables#supported-datatypes

Best Regards,
Candido

**Comment by georgikoemdzhiev** [comment]
> Hi @georgikoemdzhiev
> 
> The SQLImporter utility connects to the source database, runs the query, and inserts data into the Omnisci database (creating the target table with inferred datatypes if it doesn't exist).
> If you specify a query that can't run in the source, you get this kind of error.
> 
> Checking the denodo documentation, it looks like it doesn't support the tinyint data type, but it's able to cast from SMALLINT, and for this reason, the first query failed, while the second worked.
> 
> Anyway, OmnisciDB supports decimals too, and you can use multiple encoding to save space (from 16 to 64 bits)
> use this link as a reference for datatypes you can use with OmnisciDB on 5.6 Release
> 
> https://docs.omnisci.com/sql/data-definition-ddl/tables#supported-datatypes
> 
> Best Regards,
> Candido

Thank you for the explanation Candido. That makes sense. The only reason why our team is trying to use `TINYINT` as a destination type (i.e. in omniscidb) is to reduce our VRAM footprint. Would you say that our only option in the above situation is to change the destination type from `TINYINT` to `DECIMAL(1,0)`?

Thank you in advance!

Kind regards,
Georgi
Software engineer at IHS Markit

**Comment by dwayneberry** [comment]
Hi
DECIMAL(1,0) is still going to be 2 bytes in OmniSci.
So if you are set on using SqlImporter, which will not allow larger type of int into smaller (ie will reject attempt's to load SMALLINT -> TINYINT) you will need to declare the OmniSci column as SMALLINT.
If you could extract the data to CSV and then load via COPY you could go direct to TINYINT

**Comment by georgikoemdzhiev** [comment]
Thank you! Will try to use `SMALLINT` 🙂

**Comment by georgikoemdzhiev** [comment]
@dwayneberry @cdessanti I have tried to declare the `column1` as `SMALLINT` like so

Create table query:
```
CREATE TABLE A(
column1 SMALLINT
);
```

select query:
```
SELECT cast(column1323 as SMALLINT) as column1 from denododb
```

However, I am getting this `ERROR` from the SQLImporter:

```
2021-06-23 09:48:52 INFO  SQLImporter:executeQuery:352 - Connecting to database url :jdbc:vdb://denodo.com:9999/?queryTimeout=3600000
2021-06-23 09:49:27 ERROR SQLImporter:verifyColumnSignaturesMatch:666 - Source and destination types for column column1 do not match. Please make sure that type, precision and scale are exactly the same
```

**Comment by cdessanti** [comment]
Hi @georgikoemdzhiev,

I'm not an expert of denodo... well, to be honest, I never used it in my entire career, and looking at the docs, it's not clear what is the real type when you cast to tinyint, that's it's not a native type of denodo VDB (probably is casting to a decimal or an integer)

I will check if there is something wrong with our tool, but consider an ELT approach to use tinyint or other data types that you can't transform directly in the source.

To do that, import into a temporary table with the "select column from table" query, and then run a CTAS or IAS to create and populate the target table casting to the desired type.

here is a link to the cast supported between types in omnisci

https://docs.omnisci.com/sql/data-manipulation-dml/sql-capabilities#type-cast-support.

I tried to populate the target table casting a decimal to a tinyint for 600M of records is around 44s, with a throughput of about 14M rows/sec, so it shouldn't add so much time to the workflow of ingestion.

This is the statement I used to create the final target table on Omnisci and top the "temporary table" that SQLImporter has created.

create table discount_tinyint as select cast(DISCOUNT*100 as tinyint) from temp_discount_dec;
drop temp_discount_dec;

If the space is a concern, you can create the "temporary" table as a real temporary table with CREATE TEMPORARY TABLE temp_discount_dec, with the right data type, ingest data with SQLImporter; proper temporary tables in omnisci are in-memory, and they are not materialized to disk, and they don't survive a server restart.

I hope you will find that information useful.

Regards,
Candido

**Comment by georgikoemdzhiev** [comment]
> 
> 
> Hi @georgikoemdzhiev,
> 
> I'm not an expert of denodo... well, to be honest, I never used it in my entire career, and looking at the docs, it's not clear what is the real type when you cast to tinyint, that's it's not a native type of denodo VDB (probably is casting to a decimal or an integer)
> 
> I will check if there is something wrong with our tool, but consider an ELT approach to use tinyint or other data types that you can't transform directly in the source.
> 
> To do that, import into a temporary table with the "select column from table" query, and then run a CTAS or IAS to create and populate the target table casting to the desired type.
> 
> here is a link to the cast supported between types in omnisci
> 
> https://docs.omnisci.com/sql/data-manipulation-dml/sql-capabilities#type-cast-support.
> 
> I tried to populate the target table casting a decimal to a tinyint for 600M of records is around 44s, with a throughput of about 14M rows/sec, so it shouldn't add so much time to the workflow of ingestion.
> 
> This is the statement I used to create the final target table on Omnisci and top the "temporary table" that SQLImporter has created.
> 
> create table discount_tinyint as select cast(DISCOUNT*100 as tinyint) from temp_discount_dec;
> drop temp_discount_dec;
> 
> If the space is a concern, you can create the "temporary" table as a real temporary table with CREATE TEMPORARY TABLE temp_discount_dec, with the right data type, ingest data with SQLImporter; proper temporary tables in omnisci are in-memory, and they are not materialized to disk, and they don't survive a server restart.
> 
> I hope you will find that information useful.
> 
> Regards,
> Candido

Thank you Candido. I think the issue is coming from our source data type in denodo (i.e. DECIMAL) and something was going wrong during the casting during ingestion. We decided to use a bigger data type in Omnisci as we could not get `TINYINT` to work. We chose `DECIMAL(1,0)` to simulate an integer. I am aware that consumes more memory (2 bytes instead of 1 for SMALLINT) but our team is fine with this.
