### ISSUE TITLE
Failure in compiling the Omniscidb on Ubuntu 20.04 lts, the error is nvcc fatal   : Value 'c++17' is not defined for option 'std'

### ISSUE THREAD

**Issue by cyberspicecai** [omnisci/omniscidb#664]
OS info:
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
CUDA and GPU info:
 nvidia-smi
Sat Jul  3 17:30:01 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| 39%   36C    P8    10W / 140W |    128MiB /  6076MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1584      C   ...mnisci/bin/omnisci_server       61MiB |
|    0   N/A  N/A      1784      G   /usr/lib/xorg/Xorg                 56MiB |
|    0   N/A  N/A      1955      G   /usr/bin/gnome-shell                5MiB |
+-----------------------------------------------------------------------------+
The error is following .
[  1%] Generating gen-cpp/CalciteServer.cpp, gen-cpp/calciteserver_types.cpp, gen-cpp/completion_hints_types.cpp, gen-cpp/extension_functions_types.cpp
[  1%] Generating bin/omnisci-utility-5.7.0-SNAPSHOT.jar, bin/omnisci-jdbc-5.7.0-SNAPSHOT.jar, bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar
[  2%] Building C object ThirdParty/bcrypt/CMakeFiles/bcrypt.dir/crypt_blowfish/crypt_blowfish.c.o
[  2%] Building CXX object OSDependent/Unix/CMakeFiles/OSDependent.dir/omnisci_glob.cpp.o
[  2%] Building C object ThirdParty/bcrypt/CMakeFiles/bcrypt.dir/crypt_blowfish/crypt_gensalt.c.o
[  3%] Building CXX object Shared/CMakeFiles/ThriftClient.dir/ThriftClient.cpp.o
Scanning dependencies of target calciteserver_thrift
[  3%] Building CXX object Logger/CMakeFiles/Logger.dir/Logger.cpp.o
[  3%] Building C object ThirdParty/bcrypt/CMakeFiles/bcrypt.dir/crypt_blowfish/wrapper.c.o
[  3%] Building CXX object OSDependent/Unix/CMakeFiles/OSDependent.dir/omnisci_path.cpp.o
[  3%] Building C object ThirdParty/bcrypt/CMakeFiles/bcrypt.dir/bcrypt.c.o
[  3%] Linking C static library libbcrypt.a
[  3%] Linking CXX static library libThriftClient.a
[  3%] Built target bcrypt
[  3%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/gen-cpp/CalciteServer.cpp.o
[  3%] Building CXX object OSDependent/Unix/CMakeFiles/OSDependent.dir/omnisci_hostname.cpp.o
Scanning dependencies of target mapd_thrift
Scanning dependencies of target QueryEngineCudaTargets
[  3%] Generating cuda_mapd_rt.fatbin
[  4%] Building CXX object OSDependent/Unix/CMakeFiles/OSDependent.dir/omnisci_fs.cpp.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
make[2]: *** [QueryEngine/CMakeFiles/QueryEngineCudaTargets.dir/build.make:84: QueryEngine/cuda_mapd_rt.fatbin] Error 1
make[1]: *** [CMakeFiles/Makefile2:2114: QueryEngine/CMakeFiles/QueryEngineCudaTargets.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/gen-cpp/calciteserver_types.cpp.o
[  4%] Built target ThriftClient
[  4%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/gen-cpp/completion_hints_types.cpp.o
[  4%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/gen-cpp/extension_functions_types.cpp.o
[  4%] Linking CXX static library libLogger.a
[  4%] Linking CXX static library libOSDependent.a
[  4%] Building C object ThirdParty/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
[  5%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/OmniSci.cpp.o
[  5%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/omnisci_types.cpp.o
[  5%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/common_types.cpp.o
[  5%] Built target OSDependent
[  5%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/completion_hints_types.cpp.o
[  6%] Linking C static library libsqlite3.a
[  6%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/serialized_result_set_types.cpp.o
[  6%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/extension_functions_types.cpp.o
[  6%] Built target sqlite3
[  6%] Linking CXX static library libmapd_thrift.a
[  7%] Linking CXX static library libcalciteserver_thrift.a
[  7%] Built target Logger
[  7%] Built target calciteserver_thrift
[  7%] Built target mapd_thrift

Pls check if Ubuntu 20.04 is ok or Ubuntu 18.04 is must.

**Comment by alexbaden** [comment]
What does `nvcc --version` return? At first glance, sounds like the cuda version needs to be updated.

**Comment by cyberspicecai** [comment]
check@check-BANFF13:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


> 
> 
> What does `nvcc --version` return? At first glance, sounds like the cuda version needs to be updated.
Just follow the official guide and install the CUDA

**Comment by alexbaden** [comment]
Try upgrading to cuda 11. I believe c++17 support was introduced in 11.0, but any of the 11 lineage should work.

**Comment by cyberspicecai** [comment]
thanks. 
Seems that the official guide is misleading. The requirement is CUDA 11， but the version of Ubuntu repo is 10.

Anyway, thanks again.

CUDA
Recent versions of Ubuntu provide the NVIDIA CUDA Toolkit and drivers in the standard repositories. To install:
sudo apt install -y \
    nvidia-cuda-toolkit

> 
> Try upgrading to cuda 11. I believe c++17 support was introduced in 11.0, but any of the 11 lineage should work.
