### ISSUE TITLE
Question: Comparison to PostgreSQL syntax

### ISSUE THREAD

**Issue by Alex-Monahan** [omnisci/omniscidb#667]
Hi all!

I did some googling and couldn't find a good answer to this... How similar is OmniSci's SQL dialect to Postgres? I know OmniSci leverages Apache Calcite, but I couldn't find any Calcite vs. Postgres comparisons either. 

It's a bit of an odd question, but I'd like to see how easily DuckDB could be integrated into Modin, since DuckDB uses the Postgres query parser and Modin supports an OmniSci back end.

Thank you!!
-Alex

**Comment by ienkovich** [comment]
Hi!

Modin backend for OmniSci doesn't use SQL actually. It queries OmniSci with a serialized relational algebra tree in JSON format.

**Comment by cdessanti** [comment]
Hi,

My understanding is that Calcite implements a standard SQL as PostgreSQL, so the dialects should be quite similar, but there are some differences; Calcite, as an example, is missing the bitwise logical operators in the parser, so to implement them with Calcite, you have to define functions (take this post in the community as an example https://community.omnisci.com/t/bitwise-operation-support-in-omniscidb/2534).

You can also extend calcite, so you can have functions that are not present on Postgres and, more likely) vice-versa, but I'm not sure if you care about that.

I'm sorry if I haven't exactly replied to your question; I hope those considerations will be helpful to your evaluation

**Comment by Alex-Monahan** [comment]
Questions answered!
