### ISSUE TITLE
Is there a way to disable query cache?

### ISSUE THREAD

**Issue by dongheuw** [omnisci/omniscidb#717]
Hi there,

I'm trying to benchmark OmnisciDB via pyomnisci. Is there a way to disable query cache (both for CPU and GPU) between runs for a single query, i.e., disabling omnisci to use any (final or intermediate) result of the previously run queries while letting it use the tables loaded in memory from disk?

Thanks so much,
Dong

**Comment by cdessanti** [comment]
HI @dongheuw,

We don't use ant result cache for final or intermediate results with just one exception; the estimator result cache for some high cardinality queries.

You can disable setting the parameter --use-estimator-result-cache to false, but I'm not sure you want to disable it.

Other than that, we cache the data reads to CPU and GPU caches, the query plans, and the index we build for hash and range joins, but right now, we don't cache any results, so every result of your query reflects the data you have in the DB.

Regards,
Candido

**Comment by dongheuw** [comment]
Hi @cdessanti,

Thanks so much for your prompt reply.

Is there a way to disable the cache for "the index we build for hash and range joins"?

Thanks,
Dong

**Comment by cdessanti** [comment]
Hi,

the parameter to disable is called --use-hash-table-cache yes.
the data-recycler is about metadata and it's relatively a new parameter, but you can disable it too.

**Comment by dongheuw** [comment]
Thank you!
